import {
  FaReact,
  FaNodeJs,
  FaDocker,
  FaGitAlt,
  FaGithub,
  FaFigma,
  FaAws,
} from "react-icons/fa";

import {
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiPrisma,
  SiMysql,
  SiPostgresql,
  SiPython,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiLinux,
  SiPhp,
  SiLaravel,
  SiFlutter,
  SiGitlab,
  SiGithubactions,
} from "react-icons/si";

export const techStack = [
  { icon: FaReact, name: "React" },
  { icon: SiNextdotjs, name: "Next.js" },
  { icon: SiTypescript, name: "TypeScript" },
  { icon: SiTailwindcss, name: "Tailwind CSS" },
  { icon: FaNodeJs, name: "Node.js" },
  { icon: SiPython, name: "Python" },
  { icon: SiDjango, name: "Django" },
  { icon: SiFlask, name: "Flask" },
  { icon: SiFastapi, name: "FastAPI" },
  { icon: SiPhp, name: "PHP" },
  { icon: SiLaravel, name: "Laravel" },
  { icon: SiFlutter, name: "Flutter" },
  { icon: SiPrisma, name: "Prisma" },
  { icon: SiMysql, name: "MySQL" },
  { icon: SiPostgresql, name: "PostgreSQL" },
  { icon: FaDocker, name: "Docker" },
  { icon: SiGithubactions, name: "CI/CD" },
  { icon: FaAws, name: "AWS" },
  { icon: SiLinux, name: "Linux" },
  { icon: FaGitAlt, name: "Git" },
  { icon: FaGithub, name: "GitHub" },
  { icon: SiGitlab, name: "GitLab" },
  { icon: FaFigma, name: "Figma" },
];
