import type { Service } from "@/types/service";

export const mockServices: Service[] = [
  {
    id: "1",
    title: "Website Development",
    slug: "website-development",
    shortDescription: "Modern high-performance business websites.",
    description:
      "We build scalable, SEO-friendly, responsive websites using Next.js, React and modern technologies.",
    icon: "globe",
    image: "/images/services/web-development.jpg",
    category: "web-development",
    status: "active",
    featured: true,
    published: true,
    priceFrom: 499,
    deliveryTime: "2-4 weeks",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
    ],
    order: 1,
    createdAt: "2026-01-10",
    updatedAt: "2026-06-25",
  },
  {
    id: "2",
    title: "UI / UX Design",
    slug: "ui-ux-design",
    shortDescription: "Premium user interface and experience design.",
    description:
      "Beautiful interfaces with user-focused experiences designed in Figma and implemented with modern frontend technologies.",
    icon: "palette",
    image: "/images/services/ui-ux.jpg",
    category: "ui-ux-design",
    status: "active",
    featured: true,
    published: true,
    priceFrom: 299,
    deliveryTime: "1-2 weeks",
    technologies: [
      "Figma",
      "Design Systems",
      "Wireframes",
    ],
    order: 2,
    createdAt: "2026-02-12",
    updatedAt: "2026-06-18",
  },
  {
    id: "3",
    title: "SEO Optimization",
    slug: "seo-optimization",
    shortDescription: "Improve search rankings and organic traffic.",
    description:
      "Technical SEO, on-page optimization, performance improvements and structured metadata implementation.",
    icon: "search",
    image: "/images/services/seo.jpg",
    category: "seo",
    status: "draft",
    featured: false,
    published: false,
    priceFrom: 199,
    deliveryTime: "1 week",
    technologies: [
      "Technical SEO",
      "Schema",
      "Analytics",
    ],
    order: 3,
    createdAt: "2026-03-01",
    updatedAt: "2026-06-20",
  },
];