import type { Project } from "@/types/project";

export const projectData: Project[] = [
  {
    id: "1",
    title: "Premium Digital Agency",
    slug: "premium-digital-agency",
    description: "Modern agency website built with Next.js 15.",
    thumbnail: "https://picsum.photos/seed/digital-agency-web/1200/800",
    category: "web",
    status: "active",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
    ],
    client: "Internal",
    liveUrl: "https://agency.example.com",
    featured: true,
    published: true,
    views: 12540,
    createdAt: "2026-01-12",
    updatedAt: "2026-07-06",
  },
  {
    id: "2",
    title: "Restaurant Landing Page",
    slug: "restaurant-landing-page",
    description: "Premium restaurant marketing website.",
    thumbnail: "https://picsum.photos/seed/restaurant-landing/1200/800",
    category: "web",
    status: "completed",
    technologies: ["Next.js", "Tailwind CSS", "Framer Motion"],
    client: "Foodies",
    featured: false,
    published: true,
    views: 6842,
    createdAt: "2026-02-08",
    updatedAt: "2026-05-20",
  },
  {
    id: "3",
    title: "Healthcare Dashboard",
    slug: "healthcare-dashboard",
    description: "Hospital management admin dashboard.",
    thumbnail: "https://picsum.photos/seed/healthcare-dashboard/1200/800",
    category: "ui-ux",
    status: "active",
    technologies: ["React", "TypeScript", "Figma"],
    client: "City Hospital",
    featured: true,
    published: false,
    views: 3180,
    createdAt: "2026-03-14",
    updatedAt: "2026-06-25",
  },
  {
    id: "4",
    title: "Real Estate Platform",
    slug: "real-estate-platform",
    description: "Property listing platform with search.",
    thumbnail: "https://picsum.photos/seed/real-estate-platform/1200/800",
    category: "web",
    status: "draft",
    technologies: ["Next.js", "Prisma", "PostgreSQL"],
    client: "Dream Homes",
    featured: false,
    published: false,
    views: 0,
    createdAt: "2026-06-01",
    updatedAt: "2026-06-18",
  },
  {
    id: "5",
    title: "Fitness Mobile App",
    slug: "fitness-mobile-app",
    description: "Workout tracking mobile application.",
    thumbnail: "https://picsum.photos/seed/fitness-mobile-app/1200/800",
    category: "mobile",
    status: "completed",
    technologies: ["React Native", "Expo", "Firebase"],
    client: "FitLife",
    featured: true,
    published: true,
    views: 9470,
    createdAt: "2026-01-28",
    updatedAt: "2026-04-19",
  },
  {
    id: "6",
    title: "Brand Identity Kit",
    slug: "brand-identity-kit",
    description: "Complete branding system.",
    thumbnail: "https://picsum.photos/seed/brand-identity-kit/1200/800",
    category: "branding",
    status: "archived",
    technologies: ["Illustrator", "Photoshop", "Figma"],
    client: "Nova Studio",
    featured: false,
    published: true,
    views: 2510,
    createdAt: "2025-11-16",
    updatedAt: "2026-02-02",
  },
  {
    id: "7",
    title: "Travel Booking Website",
    slug: "travel-booking",
    description: "Online travel booking platform.",
    thumbnail: "https://picsum.photos/seed/travel-booking-site/1200/800",
    category: "web",
    status: "active",
    technologies: ["Next.js", "Stripe", "TypeScript"],
    client: "TravelGo",
    featured: true,
    published: true,
    views: 11054,
    createdAt: "2026-02-12",
    updatedAt: "2026-06-30",
  },
  {
    id: "8",
    title: "Finance Dashboard",
    slug: "finance-dashboard",
    description: "Financial analytics dashboard.",
    thumbnail: "https://picsum.photos/seed/finance-dashboard/1200/800",
    category: "ui-ux",
    status: "completed",
    technologies: ["React", "Recharts", "Tailwind CSS"],
    client: "FinCorp",
    featured: false,
    published: true,
    views: 7850,
    createdAt: "2026-03-05",
    updatedAt: "2026-05-28",
  },
  {
    id: "9",
    title: "Portfolio Website",
    slug: "portfolio-website",
    description: "Developer portfolio website.",
    thumbnail: "https://picsum.photos/seed/portfolio-website/1200/800",
    category: "web",
    status: "active",
    technologies: ["Next.js", "GSAP", "MDX"],
    client: "Personal",
    featured: true,
    published: true,
    views: 14322,
    createdAt: "2026-04-01",
    updatedAt: "2026-07-02",
  },
  {
    id: "10",
    title: "Marketing Campaign",
    slug: "marketing-campaign",
    description: "Digital campaign assets.",
    thumbnail: "https://picsum.photos/seed/marketing-campaign/1200/800",
    category: "marketing",
    status: "draft",
    technologies: ["Figma", "Photoshop"],
    client: "Bright Ads",
    featured: false,
    published: false,
    views: 430,
    createdAt: "2026-06-22",
    updatedAt: "2026-07-01",
  },
];